<script lang="ts">
  import { Button } from 'ui';
  import { stexs } from '../../stexsClient';
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';
  import type { SignInInit } from 'stexs-client/src/lib/types';
  import 'iconify-icon';
  import { redirectToPreviousPage } from '$lib/stores/previousPage';
  import { superForm, superValidateSync } from 'sveltekit-superforms/client';
  import { signInConfirmSchema } from 'validation-schemas';
  import type { MFAMethod } from '$lib/types';
  import { ProgressRadial } from '@skeletonlabs/skeleton';
  import { getFlash } from 'sveltekit-flash-message/client';
  import { page } from '$app/stores';
  import { Dropdown, Radio } from 'flowbite-svelte';

  let signInInit: SignInInit;
  let type: string;
  let submitted: boolean = false;
  let requested: boolean = false;
  const flash = getFlash(page);

  const descriptions: { [key: string]: string } = {
    _selection: 'Select an authentication method.',
    totp: 'Enter the code generated by your authenticator app to proceed.',
    email: 'Enter the code sent to your email address to proceed.',
  };

  const choices: Record<string, MFAMethod> = {
    totp: {
      icon: 'arcticons:otp-authenticator',
      description: 'Authenticator App',
    },
    email: {
      icon: 'material-symbols-light:mark-email-unread-outline',
      description: 'Email',
    },
  };

  const requestCodeTypes = ['email'];

  const { form, errors, validate } = superForm(
    superValidateSync(signInConfirmSchema),
    {
      validators: signInConfirmSchema,
      validationMethod: 'oninput',
      clearOnSubmit: 'none',
    }
  );

  onMount(async () => {
    signInInit = stexs.auth.getSignInInit();

    if (
      !signInInit ||
      (signInInit !== null && new Date(signInInit.expires * 1000) < new Date())
    ) {
      return goto('/sign-in');
    }

    if (signInInit.types.length === 1) {
      type = signInInit.types[0];
    }
  });

  function checkSignInInit() {
    signInInit = stexs.auth.getSignInInit();

    if (!signInInit || new Date(signInInit.expires * 1000) < new Date()) {
      requested = false;
      $flash = {
        message: 'Your session has expired. Please sign in again.',
        classes: 'variant-ghost-error',
        timeout: 10000,
      };
      return goto('/sign-in');
    }
  }

  async function signInConfirm() {
    const result = await validate();

    if (!result.valid) return;

    submitted = true;
    checkSignInInit();

    const response = await (
      await stexs.auth.signInConfirm(type, $form.code)
    ).json();

    if (response.access_token) return redirectToPreviousPage();

    response.errors.forEach((error: { message: string }) => {
      $errors._errors === undefined
        ? ($errors._errors = [error.message])
        : $errors._errors.push(error.message);
      return;
    });

    submitted = false;
  }

  async function requestNewCode(showMessage: boolean = false) {
    checkSignInInit();

    const response = await (await stexs.auth.mfa.requestCode(type)).json();

    requested = false;

    if (response.success && showMessage) {
      $flash = {
        message: 'New authentification code successfully requested.',
        classes: 'variant-ghost-success',
        timeout: 5000,
      };
      return;
    }

    if (response.errors) {
      response.errors.forEach((error: { message: string }) => {
        $errors._errors === undefined
          ? ($errors._errors = [error.message])
          : $errors._errors.push(error.message);
        return;
      });
    }
  }

  function cancelSignInConfirm() {
    stexs.auth.cancelSignInConfirm();
    return goto('/');
  }
</script>

<div class="flex items-center justify-center h-screen">
  <div class="card p-5 variant-ghost-surface space-y-6">
    <div class="m-auto">
      <h3 class="h3 text-primary-500 text-center">
        Multi-Factor Authentication
      </h3>
      <div class="mt-3 m-auto max-w-[280px] text-center">
        {#if !type}
          {descriptions._selection}
        {:else}
          {descriptions[type]}
        {/if}
      </div>
    </div>
    {#if !type && signInInit}
      <div class="flex flex-col space-y-2">
        {#each signInInit.types as currentType}
          <Button
            on:click={async () => {
              type = currentType;
              requestCodeTypes.includes(type) && (await requestNewCode());
            }}
            class="flex variant-ringed-surface p-2 rounded-md hover:bg-surface-600 transition items-center space-x-2 justify-start"
          >
            <span class="badge variant-filled-primary"
              ><iconify-icon
                icon={choices[currentType].icon}
                class="text-[24px]"
              /></span
            >
            <p>{choices[currentType].description}</p>
          </Button>
        {/each}
      </div>
      <Button
        class="variant-ringed-surface hover:bg-surface-600"
        value="Cancel"
        on:click={cancelSignInConfirm}>Cancel</Button
      >
    {:else if type}
      {#if $errors._errors && Array.isArray($errors._errors)}
        <ul class="whitespace-normal text-[12px] text-error-400 text-center">
          {#each $errors._errors as error (error)}
            <li>{error}</li>
          {/each}
        </ul>
      {/if}
      <form
        class="space-y-6"
        autocomplete="off"
        on:submit|preventDefault={signInConfirm}
      >
        <label for="code" class="label">
          <span>Code</span>
          <input
            id="code"
            class="input"
            type="text"
            required
            bind:value={$form.code}
          />
        </label>
        <div class="flex justify-between">
          <Button
            class="variant-ringed-surface hover:bg-surface-600"
            value="Cancel"
            on:click={cancelSignInConfirm}>Cancel</Button
          >
          {#if submitted}
            <Button
              type="submit"
              class="variant-filled-primary opacity-50 cursor-not-allowed"
              disabled
            >
              <ProgressRadial
                stroke={40}
                strokeLinecap="round"
                class="w-[24px]"
              />
            </Button>
          {:else}
            <Button type="submit" class="variant-filled-primary">Submit</Button>
          {/if}
        </div>
      </form>
      {#if (signInInit && signInInit.types.length > 1) || requestCodeTypes.includes(type)}
        <hr class="!border-t-2" />
        <div class="flex justify-between">
          {#if signInInit.types.length > 1}
            <Button>
              <span class="badge variant-filled-primary">
                <iconify-icon icon={choices[type].icon} class="text-[24px]" />
              </span>
              <iconify-icon
                icon="iconamoon:arrow-down-2-duotone"
                class="text-[24px]"
              />
            </Button>
            <Dropdown
              class="absolute left-[-38px] bg-surface-800 rounded-md p-2 space-y-2 border border-solid border-surface-500"
            >
              {#each signInInit.types as currentType}
                <Radio bind:group={type} value={currentType} custom>
                  <div
                    class="flex justify-start cursor-pointer variant-ghost-surface p-2 rounded-md hover:bg-surface-500 peer-checked:bg-surface-500 peer-checked:cursor-default transition w-full items-center"
                  >
                    <span class="badge variant-filled-primary">
                      <iconify-icon
                        icon={choices[currentType].icon}
                        class="text-[24px]"
                      />
                    </span>
                    <p class="ml-2">{choices[currentType].description}</p>
                  </div>
                </Radio>
              {/each}
            </Dropdown>
          {/if}
          {#if requestCodeTypes.includes(type)}
            {#if requested}
              <Button
                class="variant-ghost-secondary opacity-50 cursor-not-allowed w-[130px]"
              >
                <ProgressRadial
                  stroke={40}
                  strokeLinecap="round"
                  class="w-[24px]"
                />
              </Button>
            {:else}
              <Button
                class="variant-ghost-secondary"
                on:click={async () => {
                  requested = true;
                  await requestNewCode(true);
                }}>Resend code</Button
              >
            {/if}
          {/if}
        </div>
      {/if}
    {/if}
  </div>
</div>
