INSERT INTO public.scopes (name, description, type) VALUES
    ('friends.read', 'Read access to the user\'s friend list.', 'user'),
    ('items.read', 'Read items.', 'client'),
    ('items.update', 'Update items.', 'client'),
    ('items.delete', 'Delete items.', 'client'),
    ('items.insert', 'Create new items.', 'client'),
    ('inventory.read', 'Read items in the user\'s inventory.', 'user'),
    ('inventory.update', 'Update items in the user\'s inventory.', 'user'),
    ('inventory.delete', 'Delete existing items from the user\'s inventory.', 'user'),
    ('inventory.insert', 'Insert new items to the user\'s inventory.', 'user'),
    ('profile.read', 'Read user\'s profile.', 'user'),
    ('project.read', 'Read projects.', 'client'),
    ('project.update', 'Update projects.', 'client'),
    ('project.members.read', 'Read project members list.', 'client'),
    ('project.members.update', 'Update members in project.', 'client'),
    ('project.members.delete', 'Remove members from project.', 'client'),
    ('project.requests.read', 'Read project requests list.', 'client'),
    ('project.requests.update', 'Update requests in project.', 'client'),
    ('project.requests.delete', 'Delete requests from project.', 'client'),
    ('project.requests.insert', 'Create new requests for project.', 'client'),
    ('organization.read', 'Read organization.', 'client'),
    ('organization.update', 'Update organization.', 'client'),
    ('organization.members.read', 'Read organization members list.', 'client'),
    ('organization.members.update', 'Update members in organization.', 'client'),
    ('organization.members.delete', 'Delete members from organization.', 'client'),
    ('organization.requests.read', 'Read organization requests list.', 'client'),
    ('organization.requests.update', 'Update requests in organization.', 'client'),
    ('organization.requests.delete', 'Delete requests from organization.', 'client'),
    ('organization.requests.insert', 'Create new requests for organization.', 'client');
