REVOKE INSERT (name, parameter, project_id, creator_id, is_private) ON TABLE public.items FROM authenticated;
REVOKE UPDATE (name, parameter, project_id, creator_id, is_private) ON TABLE public.items FROM authenticated;
REVOKE DELETE ON TABLE public.items FROM authenticated;
REVOKE SELECT ON TABLE public.items FROM anon;
REVOKE SELECT ON TABLE public.items FROM authenticated;
REVOKE INSERT (item_id, user_id, amount, parameter) ON TABLE public.inventories FROM authenticated;
REVOKE UPDATE (amount, parameter) ON TABLE public.inventories FROM authenticated;
REVOKE DELETE ON TABLE public.inventories FROM authenticated;
REVOKE SELECT ON TABLE public.inventories FROM anon;
REVOKE SELECT ON TABLE public.inventories FROM authenticated;
REVOKE INSERT (user_id, friend_id) ON TABLE public.friends FROM authenticated;
REVOKE DELETE ON TABLE public.friends FROM authenticated;
REVOKE SELECT ON TABLE public.friends FROM anon;
REVOKE SELECT ON TABLE public.friends FROM authenticated;
REVOKE INSERT (requester_id, addressee_id) ON TABLE public.friend_requests FROM authenticated;
REVOKE DELETE ON TABLE public.friend_requests FROM authenticated;
REVOKE SELECT ON TABLE public.friend_requests FROM anon;
REVOKE SELECT ON TABLE public.friend_requests FROM authenticated;
REVOKE INSERT (blocker_id, blocked_id) ON TABLE public.blocked FROM authenticated;
REVOKE DELETE ON TABLE public.blocked FROM authenticated;
REVOKE SELECT ON TABLE public.blocked FROM anon;
REVOKE SELECT ON TABLE public.blocked FROM authenticated;
REVOKE INSERT (organization_id, member_id, role) ON TABLE public.organization_members FROM authenticated;
REVOKE UPDATE (role) ON TABLE public.organization_members FROM authenticated;
REVOKE DELETE ON TABLE public.organization_members FROM authenticated;
REVOKE SELECT ON TABLE public.organization_members FROM anon;
REVOKE SELECT ON TABLE public.organization_members FROM authenticated;
REVOKE INSERT (project_id, member_id, role) ON TABLE public.project_members FROM authenticated;
REVOKE UPDATE (role) ON TABLE public.project_members FROM authenticated;
REVOKE DELETE ON TABLE public.project_members FROM authenticated;
REVOKE SELECT ON TABLE public.project_members FROM anon;
REVOKE SELECT ON TABLE public.project_members FROM authenticated;
REVOKE INSERT (project_id, addressee_id, role) ON TABLE public.project_requests FROM authenticated;
REVOKE UPDATE (role) ON TABLE public.project_requests FROM authenticated;
REVOKE DELETE ON TABLE public.project_requests FROM authenticated;
REVOKE SELECT ON TABLE public.project_requests FROM anon;
REVOKE SELECT ON TABLE public.project_requests FROM authenticated;
REVOKE INSERT (organization_id, addressee_id, role) ON TABLE public.organization_requests FROM authenticated;
REVOKE UPDATE (role) ON TABLE public.organization_members FROM authenticated;
REVOKE DELETE ON TABLE public.organization_requests FROM authenticated;
REVOKE SELECT ON TABLE public.organization_requests FROM anon;
REVOKE SELECT ON TABLE public.organization_requests FROM authenticated;

DROP TRIGGER friend_insert_trigger ON public.friends;
DROP FUNCTION friend_insert();
DROP TRIGGER friend_delete_trigger ON public.friends;
DROP FUNCTION friend_delete();

DROP TABLE public.blocked;
DROP TABLE public.friend_requests;
DROP TABLE public.friends;
DROP TABLE public.inventories;
DROP TABLE public.items;
DROP TABLE public.project_members;
DROP TABLE public.project_requests;
DROP TABLE public.organization_members;
DROP TABLE public.organization_requests;

REVOKE USAGE, SELECT ON SEQUENCE blocked_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE friends_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE friend_requests_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE inventories_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE items_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE oauth2_app_scopes_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE oauth2_apps_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE organization_members_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE organizations_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE organization_requests_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE project_members_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE projects_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE project_requests_id_seq FROM authenticated;
REVOKE USAGE, SELECT ON SEQUENCE scopes_id_seq FROM authenticated;
