<script lang="ts">
	import { debounce } from 'lodash';
    import Button from './Button.svelte';
    import Icon from '@iconify/svelte';
    import Input from './Input.svelte';
    import { VerifyCode } from 'validation-schemas';
    import { superForm, superValidateSync } from 'sveltekit-superforms/client';
    import { Dropdown, Radio } from 'flowbite-svelte';

    export let cancel: () => void;
    export let confirm: (code: string) => Promise<void>;
    export let flash;
    export let stexs;
    export let types;
    export let type: string = '_selection';
    export let confirmErrors = [];

    type MFAMethod = {
        icon: string;
        description: string;
    };

    let submitted: boolean = false;
    let requested: boolean = false;
    let codeInput: HTMLInputElement;

    const descriptions: { [key: string]: string } = {
        _selection: 'Select an authentication method.',
        totp: 'Enter the code generated by your authenticator app to proceed.',
        email: 'Enter the code sent to your email address to proceed.',
    };
    const choices: Record<string, MFAMethod> = {
        totp: {
            icon: 'arcticons:otp-authenticator',
            description: 'Authenticator App',
        },
        email: {
            icon: 'material-symbols-light:mark-email-unread-outline',
            description: 'Email',
        },
    };
    const requestCodeTypes = ['email'];

    let codeRequested: { [key: string]: boolean  } = {
        email: false
    };

    const { form, errors, validate } = superForm(superValidateSync(VerifyCode), {
        validators: VerifyCode,
        validationMethod: 'oninput',
        clearOnSubmit: 'none',
    });

    async function requestNewCode(type: string, showMessage: boolean = false) {
        if (!codeRequested[type]) codeRequested[type] = true;

        const response = await (await stexs.auth.mfa.requestCode(type)).json();

        requested = false;

        if (response.success && showMessage) {
            $flash = {
                message: 'New authentification code successfully requested.',
                classes: 'variant-glass-success',
                timeout: 5000,
            };
            return;
        }

        if (response.errors) {
            response.errors.forEach((error: { message: string }) => {
                $errors._errors === undefined
                ? ($errors._errors = [error.message])
                : $errors._errors.push(error.message);
                return;
            });
        }
    }

    async function confirmCode() {
        const result = await validate();

        if (!result.valid) return;

        submitted = true;

        await confirm($form.code);
        
        confirmErrors.forEach((error: { message: string }) => {
            $errors._errors === undefined
                ? ($errors._errors = [error.message])
                : $errors._errors.push(error.message);
            return;
        });

        submitted = false;
    }

    $: {
        if (type !== '_selection' && codeInput) codeInput.focus();
    }

    $: $form.code = $form.code.toUpperCase();
</script>

<div class="card p-5 space-y-6">
    <div class="m-auto">
        <h3 class="h3 text-primary-500 text-center">
            Multi-Factor Authentication 
        </h3>
        <div class="mt-3 m-auto max-w-[280px] text-center">
            {#if type === '_selection'}
                {descriptions._selection}
            {:else}
                {descriptions[type]}
            {/if}
        </div>
    </div>
    {#if type === '_selection'}
        <div class="flex flex-col space-y-2">
            {#each types as currentType}
                <Button
                    on:click={async () => {
                        type = currentType;
                        requestCodeTypes.includes(type) && (await requestNewCode(currentType));
                    }}
                    class="flex variant-ringed-surface p-2 rounded-md hover:bg-surface-600 transition items-center space-x-2 justify-start"
                >
                <span class="badge variant-filled-primary">
                    <Icon
                        icon={choices[currentType].icon}
                        class="text-[24px]"
                    />
                </span>
                <p>{choices[currentType].description}</p>
                </Button>
            {/each}
        </div>
        <Button
            class="variant-ringed-surface hover:bg-surface-600"
            value="Cancel"
            on:click={cancel}>Cancel</Button
        >
    {:else if type}
        <div class="flex flex-row space-x-2 justify-center">
            {#if types && types.length > 1}
                <Button class="p-2 variant-ghost-surface">
                    <span class="badge variant-filled-primary rounded">
                        <Icon icon={choices[type].icon} class="text-[24px]" />
                    </span>
                    <p>{choices[type].description}</p>
                    <Icon
                        icon="iconamoon:arrow-down-2-duotone"
                        class="text-[24px]"
                    />
                </Button>
                <Dropdown
                    class="bg-surface-800 rounded-md p-2 space-y-2 border border-surface-500"
                >
                    {#each types as currentType}
                        <Radio bind:group={type} on:click={async () => {
                            if (!codeRequested[currentType] && requestCodeTypes.includes(currentType)) requestNewCode(currentType);
                        }} value={currentType} custom>
                            <div
                                class="flex justify-start cursor-pointer variant-ghost-surface p-2 rounded-md hover:bg-surface-500 peer-checked:bg-surface-500 peer-checked:cursor-default transition w-full items-center"
                            >
                            <span class="badge variant-filled-primary rounded">
                                <Icon
                                    icon={choices[currentType].icon}
                                    class="text-[24px]"
                                />
                            </span>
                                <p class="ml-2">{choices[currentType].description}</p>
                            </div>
                        </Radio>
                    {/each}
                </Dropdown>
            {/if}
            {#if requestCodeTypes.includes(type)}
                <div class="h-[48px]">
                    <Button
                        title="Resend code"
                        class="variant-ghost-secondary h-[48px] w-[48px] px-2"
                        on:click={async () => {
                            requested = true;
                            await requestNewCode(type, true);
                        }}
                        submitted={requested}
                    >
                        <Icon icon="tabler:reload" class="text-[20px]" />
                    </Button>
                </div>
            {/if}
        </div>
        {#if $errors._errors && Array.isArray($errors._errors)}
            <ul class="whitespace-normal text-[14px] text-error-400 text-center">
                {#each $errors._errors as error (error)}
                    <li>{error}</li>
                {/each}
            </ul>
        {/if}
        <form
            class="space-y-6"
            autocomplete="off"
            on:submit|preventDefault={confirmCode}
        >
            <Input
                field="code"
                required
                bind:value={$form.code}
                bind:ref={codeInput}
            >Code</Input>
            {#if $errors.code && Array.isArray($errors.code)}
                <ul class="whitespace-normal text-[14px] mt-2 text-error-400">
                {#each $errors.code as error (error)}
                    <li>{error}</li>
                {/each}
                </ul>
            {/if}
            <div class="flex justify-between">
                <Button
                    class="variant-ringed-surface hover:bg-surface-600"
                    value="Cancel"
                    on:click={cancel}>Cancel</Button
                >
                <Button type="submit" class="variant-filled-primary" {submitted}
                    >Submit</Button
                >
            </div>
        </form>
    {/if}
</div>
