INSERT INTO public.scopes (name, description, type) VALUES
    ('friends.read', 'Read access to the user''s friend list.', 'user'),
    ('items.read', 'Read items.', 'client'),
    ('items.update', 'Update items.', 'client'),
    ('items.delete', 'Delete items.', 'client'),
    ('items.write', 'Create new items.', 'client'),
    ('inventory.read', 'Read items in the user''s inventory.', 'user'),
    ('inventory.update', 'Update items in the user''s inventory.', 'user'),
    ('inventory.delete', 'Delete existing items from the user''s inventory.', 'user'),
    ('inventory.write', 'Write items to the user''s inventory.', 'user'),
    ('profile.read', 'Read user''s profile.', 'user'),
    ('project.read', 'Read projects.', 'client'),
    ('project.update', 'Update projects.', 'client'),
    ('project.members.read', 'Read project members list.', 'client'),
    ('project.members.update', 'Update members in project.', 'client'),
    ('project.members.delete', 'Remove members from project.', 'client'),
    ('project.requests.read', 'Read project requests list.', 'client'),
    ('project.requests.update', 'Update requests in project.', 'client'),
    ('project.requests.delete', 'Delete requests from project.', 'client'),
    ('project.requests.write', 'Create new requests for project.', 'client'),
    ('organization.read', 'Read organization.', 'client'),
    ('organization.update', 'Update organization.', 'client'),
    ('organization.members.read', 'Read organization members list.', 'client'),
    ('organization.members.update', 'Update members in organization.', 'client'),
    ('organization.members.delete', 'Delete members from organization.', 'client'),
    ('organization.requests.read', 'Read organization requests list.', 'client'),
    ('organization.requests.update', 'Update requests in organization.', 'client'),
    ('organization.requests.delete', 'Delete requests from organization.', 'client'),
    ('organization.requests.write', 'Create new requests for organization.', 'client'),
    ('friend.requests.write', 'Send friend requests for an user.', 'user'),
    ('friend.requests.read', 'Read friend requests send to an user.', 'user'),
    ('friend.requests.delete', 'Delete friend requests from an user.', 'user'),
    ('friends.write', 'Accept friend requests for an user.', 'user'),
    ('friends.delete', 'Delete friends from an user.', 'user'),
    ('blocked.read', 'Read blocked persons by an user.', 'user'),
    ('blocked.write', 'Block persons for an user.', 'user'),
    ('blocked.delete', 'Remove blocked persons from an user.', 'user'),
    ('items.thumbnail.write', 'Upload thumbnail for an item.', 'client'),
    ('organization.logo.write', 'Upload logo for an organization.', 'client'),
    ('organization.logo.delete', 'Delete logo from an organization.', 'client'),
    ('project.logo.write', 'Upload logo for a project.', 'client'),
    ('project.logo.delete', 'Delete logo from a project.', 'client');
    