"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TOTP_PERIOD = exports.TOTP_DIGITS = exports.TOTP_ALGORITHM = exports.SERVICE_NAME = exports.LOGGER_URL = exports.REDIRECT_TO_RECOVERY = exports.REDIRECT_TO_SIGN_IN = exports.JWT_EXPIRY_SIGN_IN_CONFIRM_LIMIT = exports.JWT_EXPIRY_LIMIT = exports.AUDIENCE = exports.ISSUER = exports.SIGN_IN_CONFIRM_TOKEN_SECRET = exports.REFRESH_TOKEN_SECRET = exports.ACCESS_TOKEN_SECRET = exports.SMTP_EMAIL = exports.SMTP_PWD = exports.SMTP_USER = exports.SMTP_PORT = exports.SMTP_HOST = exports.PG_URL = exports.SERVER_PORT = exports.ENV = void 0;
var dotenv_1 = require("dotenv");
(0, dotenv_1.config)();
exports.ENV = process.env.ENV;
exports.SERVER_PORT = parseInt(process.env.SERVER_PORT);
exports.PG_URL = process.env.PG_URL;
exports.SMTP_HOST = process.env.SMTP_HOST;
exports.SMTP_PORT = parseInt(process.env.SMTP_PORT);
exports.SMTP_USER = process.env.SMTP_USER;
exports.SMTP_PWD = process.env.SMTP_PWD;
exports.SMTP_EMAIL = process.env.SMTP_EMAIL;
exports.ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
exports.REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
exports.SIGN_IN_CONFIRM_TOKEN_SECRET = process.env.SIGN_IN_CONFIRM_TOKEN_SECRET;
exports.ISSUER = process.env.ISSUER;
exports.AUDIENCE = process.env.AUDIENCE;
exports.JWT_EXPIRY_LIMIT = parseInt(process.env.JWT_EXPIRY_LIMIT);
exports.JWT_EXPIRY_SIGN_IN_CONFIRM_LIMIT = parseInt(process.env.JWT_EXPIRY_SIGN_IN_CONFIRM_LIMIT);
exports.REDIRECT_TO_SIGN_IN = process.env.SIGN_IN_URL;
exports.REDIRECT_TO_RECOVERY = process.env.RECOVERY_URL;
exports.LOGGER_URL = process.env.LOGGER_URL;
exports.SERVICE_NAME = process.env.SERVICE_NAME;
exports.TOTP_ALGORITHM = process.env.TOTP_ALGORITHM;
exports.TOTP_DIGITS = parseInt(process.env.TOTP_DIGITS);
exports.TOTP_PERIOD = parseInt(process.env.TOTP_PERIOD);
